[Launch]
ProgramExecutable64=LocalSend64\localsend_app.exe
ProgramExecutableARM64=LocalSendarm64\localsend_app.exe
;MinOS=10

[FilesMove]
settings\settings.json=%FullAppDir%

[FileWrite1]
Type=Replace
File=%PAL:DataDir%\settings\settings.json
Find=%PAL:LastDrive%\\
Replace=%PAL:Drive%\\