[Launch]
ProgramExecutable64=LocalSend\localsend_app.exe
;MinOS=10

[FilesMove]
settings\settings.json=%PAL:AppDir%\LocalSend

[FileWrite1]
Type=Replace
File=%PAL:DataDir%\settings\settings.json
Find=%PAL:LastDrive%\\
Replace=%PAL:Drive%\\

[FileWrite2]
Type=Replace
File=%PAL:DataDir%\settings\settings.json
Find=DATADOWNLOAD
Replace=%PAL:DataDir:DoubleBackslash%\\Downloads
